image: maven:3-jdk-8
build:
  run: mvn -B package
  <% if (DOTCI_BRANCH == 'develop') { %>
  after:
    analytics:
      - mvn -B -Dgpg.skip=true clean install
      - mvn -B sonar:sonar
      - mvn -B jacoco:report coveralls:report
  <% } %>

links:
  - image: postgres:latest
